### ISSUE TITLE
Can't play audio with pygame on macOS because mixer module is not available

### ISSUE THREAD

**Issue by pedmiston** [lupyanlab/lab-computer#1]
Here's how I installed a new psychopy environment with Anaconda on macOS. It uses pygame for audio.

```
(root) $ conda env create -f anaconda-environments/psychopy-environment-macos.yml
# creates a new conda env named "psychopy"
(root) $ source activate psychopy
(psychopy) $ cd psychopy-tests
```

When I tried to run the psychopy tests, I got an error, saying there was a missing Library, expected at "/usr/local/lib/libSDL_mixer-1.2.0.dylib", that is required for playing sounds with pygame.

```
(psychopy) psychopy-tests/$ python test_psychopy_sound.py
/Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/psychopy/sound.py:497: RuntimeWarning: use mixer: dlopen(/Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so, 2): Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib
  Referenced from: /Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so
  Reason: image not found
(ImportError: dlopen(/Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so, 2): Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib
  Referenced from: /Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so
  Reason: image not found)
  if not mixer.get_init():
Traceback (most recent call last):
  File "test_psychopy_sound.py", line 13, in <module>
    snd = sound.Sound('telephone-ring.wav')
  File "/Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/psychopy/sound.py", line 497, in __init__
    if not mixer.get_init():
  File "/Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/__init__.py", line 105, in __getattr__
    raise NotImplementedError(MissingPygameModule)
NotImplementedError: mixer module not available
(ImportError: dlopen(/Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so, 2): Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib
  Referenced from: /Users/pierce/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so
  Reason: image not found)
1.3073 	WARNING 	Monitor specification not found. Creating a temporary one...

**Comment by pedmiston** [comment]
I was able to install the missing library with Homebrew.

**Note:** Be sure to only run Homebrew from outside the anaconda environment. Otherwise it will pick up the active anaconda python and might spit out some warnings.

```
$ brew install sdl_mixer
```
