### ISSUE TITLE
Error when importing psychopy.visual: No module named Image

### ISSUE THREAD

**Issue by pedmiston** [lupyanlab/lab-computer#5]
I got this error when trying to run psychopy on Windows 10 in the lab.

```bash
C:\Users\LupyanLab\lab-computer\psychopy-tests>python test_psychopy.py
Traceback (most recent call last):
  File "test_psychopy.py", line 1, in <module>
    from psychopy import visual, core, event
  File "C:\Users\LupyanLab\Miniconda2\lib\site-packages\psychopy\visual\__init__.py", line 17, in <module>
    from .window import Window, getMsPerFrame, openWindows
  File "C:\Users\LupyanLab\Miniconda2\lib\site-packages\psychopy\visual\window.py", line 65, in <module>
    from .text import TextStim
  File "C:\Users\LupyanLab\Miniconda2\lib\site-packages\psychopy\visual\text.py", line 30, in <module>
    from psychopy.visual.basevisual import BaseVisualStim, ColorMixin
  File "C:\Users\LupyanLab\Miniconda2\lib\site-packages\psychopy\visual\basevisual.py", line 20, in <module>
    import Image
ImportError: No module named Image
```

**Comment by pedmiston** [comment]
The `Image` module comes from the old python image library `PIL` which we install as `pillow`. I got this error with `pillow=5.0.0`. I was able to get it work by installing an older version of pillow.

```bash
conda install pillow=4.0.0
```

Unfortunately, downgrading pillow in this way also causes other packages to downgrade, such as `numexpr` and `pandas` won't work without a better version of `numexpr`, so after I downgraded pillow I also had to upgrade `numexpr` to 2.4.6 or higher.

```bash
conda install numexpr=2.4.6
```

After that, I was able to get the test to work.
