### ISSUE TITLE
Error when using pygame for sound: libSDL_mixer-1.2.0.dylib not found

### ISSUE THREAD

**Issue by pedmiston** [lupyanlab/lab-computer#9]
I was intending to use pygame as the sound library for psychopy. The first error I got was a [missing dylib for SDL](https://github.com/lupyanlab/lab-computer/issues/3). I got passed that error with `brew install sdl`. Then I can import pygame without any problems.

However, I still got an error when trying to use pygame as the sound library. Here I'm running one of the sound test scripts available in the [psychopy-tests/](https://github.com/lupyanlab/lab-computer/tree/master/psychopy-tests) directory of this repo. The full traceback is below.

```
psychopy-tests/$ python test_psychopy_sound_simple.py 
/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/psychopy/sound/backend_pygame.py:86: RuntimeWarning: use mixer: dlopen(/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so, 2): Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib
  Referenced from: /usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so
  Reason: image not found
(ImportError: dlopen(/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so, 2): Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib
  Referenced from: /usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so
  Reason: image not found)
  if not mixer.get_init():
Traceback (most recent call last):
  File "test_psychopy_sound_simple.py", line 13, in <module>
    snd = sound.Sound('telephone-ring.wav')
  File "/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/psychopy/sound/backend_pygame.py", line 86, in __init__
    if not mixer.get_init():
  File "/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/__init__.py", line 105, in __getattr__
    raise NotImplementedError(MissingPygameModule)
NotImplementedError: mixer module not available
(ImportError: dlopen(/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so, 2): Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib
  Referenced from: /usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/mixer.so
  Reason: image not found)
1.4864 	WARNING 	pyo audio lib was requested but not loaded: ImportError('No module named pyo',)
1.4869 	WARNING 	Monitor specification not found. Creating a temporary one...
(psychopy) psychopy-tests/$ python test_psychopy_sound_simple.py 
1.7105 	WARNING 	pyo audio lib was requested but not loaded: ImportError('No module named pyo',)
1.7108 	WARNING 	Monitor specification not found. Creating a temporary one...
```

**Comment by pedmiston** [comment]
The relevant error is `Library not loaded: /usr/local/lib/libSDL_mixer-1.2.0.dylib`.
The missing dylib can be installed with hombrew.
`brew install sdl_mixer`
